import Onboard from '@web3-onboard/core'
import injectedModule from '@web3-onboard/injected-wallets'
import walletConnectModule from '@web3-onboard/injected-wallets'
import coinbaseModule from '@web3-onboard/injected-wallets'

const injected = injectedModule()
const walletConnect = walletConnectModule()
const coinbase = coinbaseModule()

const onboard = Onboard({
  wallets: [injected, walletConnect, coinbase],
  chains: [
    {
      id: '0x1',
      token: 'ETH',
      label: 'Ethereum Mainnet',
      rpcUrl: 'https://mainnet.infura.io/v3/<YOUR_INFURA_KEY>'
    },
    {
        id: '137',
        token: 'POL',
        label: 'Polygon Mainnet',
        rpcUrl: 'https://polygon-rpc.com/'
    },
    {
        id: '56',
        token: 'BNB',
        label: 'Binance Smart Chain Mainnet',
        rpcUrl: 'https://bsc-dataseed.binance.org/'
    },
    {
        id: '43114',
        token: 'AVAX',
        label: 'Avalanche Mainnet',
        rpcUrl: 'https://api.avax.network/ext/bc/C/rpc'
    }
    
  ],
  appMetadata: {
    name: 'Logo',
    icon: 'data:image/svg+xml:base64;PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDIwMDEwOTA0Ly9FTiIKICJodHRwOi8vd3d3LnczLm9yZy9UUi8yMDAxL1JFQy1TVkctMjAwMTA5MDQvRFREL3N2ZzEwLmR0ZCI+CjxzdmcgdmVyc2lvbj0iMS4wIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiB3aWR0aD0iODY2LjAwMDAwMHB0IiBoZWlnaHQ9IjY1MC4wMDAwMDBwdCIgdmlld0JveD0iMCAwIDg2Ni4wMDAwMDAgNjUwLjAwMDAwMCIKIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaWRZTWlkIG1lZXQiPgoKPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMDAwMDAsNjUwLjAwMDAwMCkgc2NhbGUoMC4xMDAwMDAsLTAuMTAwMDAwKSIKZmlsbD0iIzAwMDAwMCIgc3Ryb2tlPSJub25lIj4KPHBhdGggZD0iTTQyNDYgNTU0OSBjLTExOCAtMTYgLTE5MSAtNDkgLTU0NiAtMjU0IC0xMDA0IC01NzggLTExNzkgLTY4MAotMTIyMCAtNzE0IC05NSAtODAgLTE3MiAtMTk3IC0yMTcgLTMzMSAtMTcgLTUxIC0xOCAtMTE3IC0yMSAtOTc0IC0zIC04OTYgLTIKLTkyMSAxOCAtMTAwMCAzNyAtMTQ5IDExNiAtMjczIDIzMiAtMzY2IDMyIC0yNSAxMzcgLTkxIDIzNSAtMTQ3IDE0MyAtODEgNDY2Ci0yNjcgNjQ4IC0zNzMgNTE0IC0yOTggNjk3IC0zOTggNzY1IC00MTcgMTAyIC0zMCAxODIgLTM3IDI3MyAtMjQgMTQ5IDIxIDEyMwo3IDkxNyA0NjYgMzc1IDIxNiA1ODQgMzM2IDY5NCAzOTggMjEwIDEyMCAzMzIgMjY3IDM4MSA0NjIgMTMgNTEgMTUgMTkxIDE1Cjk3NSAwIDEwMjIgNCA5NjYgLTcyIDExMjAgLTMyIDY3IC01OCAxMDIgLTEyMiAxNjYgLTY4IDY3IC0xMDcgOTUgLTI0MSAxNzEKLTg4IDUwIC0yNTkgMTQ4IC0zODAgMjE4IC0yMTQgMTI0IC02MzkgMzY5IC04NzggNTA2IC0xODcgMTA3IC0zMTYgMTM5IC00ODEKMTE4eiBtMTU1IC0zMzQgYzM1IC00IDE0MSAtNjAgNDYwIC0yNDMgMjI4IC0xMzEgNTU5IC0zMjEgNzM2IC00MjMgMTc3IC0xMDEKMzIyIC0xODcgMzIzIC0xOTAgMCAtNSAtMzkwIC0yMzcgLTEwMjUgLTYwOSAtNDQgLTI2IC0xODkgLTExMSAtMzIyIC0xODkKbC0yNDIgLTE0MiAtMzQ4IDIwNSBjLTE5MSAxMTMgLTM0OSAyMDkgLTM1MCAyMTMgLTIgNSA5IDE2IDI0IDI0IDEzMiA3NSA0NzkKMjc1IDU2NiAzMjUgbDEwNyA2MyA5NSAtNTQgYzUyIC0zMCAxMzggLTgwIDE5MCAtMTEwIDUzIC0zMCA5OCAtNTUgMTAxIC01NQoxMSAwIDMxNCAxODMgMzE0IDE5MCAwIDQgLTEzMCA4MyAtMjkwIDE3NSAtNDEyIDIzNyAtNDA5IDIzNyAtNzM3IDQ3IC0xMDQKLTYxIC0zMDYgLTE3OCAtNDUwIC0yNjEgbC0yNjEgLTE1MSAtMTY0IDk3IGMtODkgNTMgLTIxNCAxMjcgLTI3NiAxNjQgbC0xMTMKNjcgNTggMzUgYzMyIDE5IDE5MSAxMTEgMzUzIDIwNCAxNjIgOTMgNDY0IDI2NiA2NzAgMzg1IDIwNyAxMTkgMzk0IDIyMSA0MTUKMjI3IDUwIDE0IDg2IDE5IDEwNSAxNSA4IC0xIDM2IC01IDYxIC05eiBtLTExOTEgLTE1MjAgYzM0NCAtMjAyIDcwMCAtNDEzCjc5MyAtNDY3IGwxNjcgLTEwMCAwIC0zODkgYzAgLTIxNCAtMiAtMzg5IC02IC0zODkgLTMgMCAtMTQzIDgwIC0zMTIgMTc3Ci0xNjkgOTcgLTMyNiAxODcgLTM0OSAyMDEgbC00MyAyNCAwIDIwMSAwIDIwMiAtMTQzIDg0IGMtNzggNDcgLTE1MiA5MSAtMTY1Cjk5IGwtMjMgMTUgMyAtMzM5IDMgLTMzOSAzMyAtNjggYzIxIC00MiA0OSAtODAgNzUgLTEwMiAyMyAtMTkgMTg2IC0xMTcgMzYyCi0yMTkgMTc2IC0xMDEgMzc0IC0yMTUgNDQwIC0yNTMgbDEyMCAtNjkgMyAtMzIyIGMxIC0xNzcgMCAtMzIyIC0zIC0zMjIgLTIgMAotNDggMjUgLTEwMiA1NyAtNTQgMzEgLTE4NiAxMDcgLTI5MyAxNjggLTEwNyA2MiAtMjQwIDEzOCAtMjk1IDE3MCAtMTg4IDEwOQotNDgwIDI3NyAtNjE1IDM1MyAtMTc3IDEwMCAtMjQwIDE2MCAtMjY5IDI1NiAtMjEgNjcgLTIxIDg0IC0yMSA5MDggMCA0NjEgMwo4MzcgOCA4MzUgNCAtMiAyODggLTE3MCA2MzIgLTM3MnogbTI4ODAgLTQ4MCBjMCAtOTI5IDIgLTg4OSAtNjIgLTk4MiAtNDEKLTYxIC0yIC0zNyAtNzE4IC00NDggLTExMyAtNjUgLTMyNiAtMTg3IC00NzUgLTI3MyAtMTQ4IC04NSAtMjg1IC0xNjMgLTMwMgotMTc0IGwtMzMgLTIwIDAgOTA5IDAgOTA4IDE1OCA5MiBjODYgNTAgMjQyIDE0MSAzNDYgMjAyIDEwNCA2MSAxOTAgMTExIDE5MgoxMTEgMiAwIDQgLTE3NyA0IC0zOTQgbDAgLTM5NSAtODIgLTQ5IGMtNDYgLTI2IC0xMjcgLTc0IC0xODAgLTEwNiBsLTk4IC01NwowIC0xOTAgMCAtMTkxIDMzIDIwIGMzMyAyMCA0MDkgMjM3IDQ4MyAyNzkgNTUgMzEgMTIwIDEwMyAxNDcgMTYxIDIyIDQ2IDIyCjU4IDI1IDU4NCBsMyA1MzcgOTcgNTcgYzM0MiAyMDIgNDQ4IDI2MyA0NTUgMjY0IDQgMCA3IC0zODAgNyAtODQ1eiIvPgo8L2c+Cjwvc3ZnPgo=',
    description: 'Conecta tu wallet para usar Logo'
  },
  theme: 'dark'
})

export default onboard